config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :archived_time_entries, only: [:index, :show, :create]
  resources :archived_weeks, only: [:index, :show, :create]
  resources :holiday_exceptions
  resources :time_entries
  resources :weeks 
  resources :tasks
  resources :projects
  resources :customers
  resources :roles
  resources :users
  resources :holidays
  resources :employment_types
  resources :customers_holidays
  resources :report_logos
  resources :features, except: [:index]
  resources :case_studies
  resources :vacation_types
  resources :shifts
  resources :project_shifts
  resources :announcements
  devise_for :users, :path => "account", :controllers => { passwords: 'passwords', registrations: 'registrations', invitations: 'invitations', :omniauth_callbacks => "users/omniauth_callbacks", :sessions => 'sessions' }
  devise_scope :user do
    match "/users/sign_in", :to => 'devise/sessions#new', via: [:get, :post]
    match "/users/sign_out", :to => 'devise/sessions#destroy', via: [:delete]
    match '/invitation/resend_invite' => 'invitations#resend_invite', via: [:post]
  end

  post '/weeks/:id(.:format)' => 'weeks#update'
  authenticated :user do
    root to: 'weeks#index', as: :authenticated_root
  end
  
  get "/get_user_projects" => "users#get_user_projects"
  post '/application_versions/get_items' => "application_versions#get_items"
  get '/application_versions/delete_item' => "application_versions#delete_item" 
  post '/application_versions/edit_item' => "application_versions#edit_item"
  get '/application_versions/acknowledge_version' => "application_versions#acknowledge_version" 

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/features' => 'static_pages#features'
  namespace :api do
    post 'social_login', to: "users#social_login"
    post 'login_user', to: "users#login_user"
    get 'login_user', to: "users#login_user"
    get 'get_weekly_time_entries', to: "time_entries#get_weekly_time_entries"
    get 'get_daily_time_entries', to: "time_entries#get_daily_time_entries"
    get 'submit_weekly_time_entry', to: "time_entries#submit_weekly_time_entry"
    get 'delete_time_entry', to: "time_entries#delete_time_entry"
    get 'get_time_entry_detail', to: "time_entries#get_time_entry_detail"
    post 'save_time_entry', to: "time_entries#save_time_entry"
    get 'get_user_projects', to: "time_entries#get_user_projects"
    get 'get_project_tasks', to: "time_entries#get_project_tasks"
    post 'save_device_info', to: "notifications#save_device_info"
    get 'remove_device_info', to: "notifications#remove_device_info"
    get 'get_customer_detail', to: "users#get_customer_detail"
    get 'get_customer_holidays', to: "users#get_customer_holidays"
    get 'agree_to_terms_and_conditions', to: "users#agree_to_terms_and_conditions"

    post 'send_entry', to: "users#post_data"
    get 'send_entry', to: "users#post_data"

    get 'get_time_entry', to: "users#get_time_entry"
    post 'get_time_entry', to: "users#get_time_entry"

    get 'get_tasks', to: "users#get_tasks"
    post 'get_tasks', to: "users#get_tasks"

    post 'update_date', to: "users#update_date"
    get 'update_date', to: "users#update_date"

    post 'get_submitted_timesheet', to: "users#get_submitted_timesheet"
    get 'get_submitted_timesheet', to: "users#get_submitted_timesheet"

    post 'approve', to: "users#approve"
    get 'approve', to: "users#approve"

    post 'reject', to: "users#reject"
    get 'reject', to: "users#reject"

    post 'submit_week', to: "users#submit_week"

    resource :sessions, only: [:create, :destroy]
  end

  post 'change_status' => 'weeks#change_status', as: :change_status
  get 'duplicate' => 'weeks#duplicate'
  get 'weeks/:id/report' => 'weeks#report'
  
  get '/dynamic_project_update' => 'projects#dynamic_project_update'
  get '/dynamic_customer_update' => 'customers#dynamic_customer_update'
  post '/add_configuration' => 'customers#add_configuration', as: :add_configuration
  get '/remove_configuration' => 'customers#remove_configuration', as: :remove_configuration

  post '/create_project_from_system' => 'projects#create_project_from_system'
  get 'show_projects/:system' => 'projects#show_projects'

  get 'projects/:id/approve/:week_id/:row_id' => 'projects#approve'
  match 'weeks/dismiss/:week_id/:row_id' => 'weeks#dismiss', via: [:get, :post]
  get 'projects/:id/reject/:week_id' => 'projects#reject'
  get 'show_project_reports' => 'projects#show_project_reports'
  post 'add_multiple_users_to_project' => "projects#add_multiple_users_to_project"
  post 'remove_multiple_users_from_project' => "projects#remove_multiple_users_from_project"
  post 'shift_modal' => "projects#shift_modal"
  get 'show_shift_reports' => "shifts#show_shift_reports"
  get 'cm_shift_report' => "shifts#cm_shift_report"
  get 'shift_report/:id' => "shifts#shift_report"
  post 'shift_report/:id' => "shifts#shift_report"
  post 'show_project_reports' => 'projects#show_project_reports'
  post 'projects/:id/deactivate_project' => 'projects#deactivate_project'
  post 'projects/:id/reactivate_project' => 'projects#reactivate_project'
  post 'time_reject' => 'weeks#time_reject'
  post 'show_hours' => 'projects#show_hours'
  post '/pending_email' => 'projects#pending_email'
  post '/customers_pending_email' => 'customers#customers_pending_email'
  post '/previous_comments' => 'weeks#previous_comments'
  post '/shared_user' => 'customers#shared_user'
  get '/add_shared_users' => 'customers#add_shared_users'
  post '/assign_shift' => 'shifts#assign_shift'
  get '/toggle_shift' => 'shifts#toggle_shift'
  post '/add_previous_week' => 'weeks#add_previous_week', as: :add_previous_week
  post '/open_previous_week_modal' => 'weeks#open_previous_week_modal'

  post '/open_edit_customer_modal' => 'customers#open_edit_customer_modal'

  post '/hours_approved' => 'customers#hours_approved', as: :hours_approved
  post '/hours_submitted' => 'customers#hours_submitted', as: :hours_submitted
  get '/users_on_project' => 'customers#users_on_project', as: :users_on_project
  get '/show_pm_projects' => 'customers#show_pm_projects', as: :show_pm_projects

  get '/show_user_reports/:id' => 'users#show_user_reports'
  post '/show_user_reports/:id' => 'users#show_user_reports'

  get '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'
  post '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'

  get '/set_default_project' => 'users#set_default_project'
  post '/update_announcement' => 'announcements#update_announcement'

  match 'accept_terms_and_condition' => 'users#accept_terms_and_condition', via: [:get, :post]
  
  get 'add_user_to_project' => "projects#add_user_to_project"
  get '/projects/:id/user_time_report' => 'projects#user_time_report'
  match 'user_account', :to => "users#user_account",  via: [:get, :post]
  match 'admin', :to => "users#admin", via: [:get, :post]
  post 'update_front_page_content' => "features#update_front_page_content"
  get 'display_data' => "users#display_data"
  get 'remove_user_from_customer' => "customers#remove_user_from_customer"
  get 'shared_user' => "customers#shared_user"
  get 'add_pm_role' => "customers#add_pm_role"
  get 'assign_proxy_role' => "customers#assign_proxy_role"
  get 'assign_cm_proxy_role' => "customers#assign_cm_proxy_role"
  get 'edit_customer_user/:user_id' => "customers#edit_customer_user"
  get '/update_user_employment' => "customers#update_user_employment"
  get 'vacation_request' => "customers#vacation_request"
  post 'vacation_request' => "customers#vacation_request"
  get 'customers/approve_vacation/:vr_id/:row_id' => 'customers#approve_vacation'
  get 'customers/reject_vacation/:vr_id/:row_id' => 'customers#reject_vacation'
  get 'customers/approve_cancel_request/:vr_id/:row_id' => 'customers#approve_cancel_request'
  get 'resend_vacation_request' => 'customers#resend_vacation_request'
  get 'cancel_vacation_request' => 'customers#cancel_vacation_request' 
  get 'customers/:id/theme' => 'customers#set_theme'
  get 'customers/:id/clear_filter' => 'customers#clear_filter', as: :clear_filter
  get 'pre_vacation_request' => "customers#pre_vacation_request"
  get 'single_vacation_request' => "weeks#single_vacation_request"

  get 'shift_change_request' => "customers#shift_change_request"
  get 'shift_request' => 'customers#shift_request'
  get 'projects/approve_shift_change/:sr_id/:row_id/:project_id' => 'projects#approve_shift_change'
  get 'projects/reject_shift_change/:sr_id/:row_id/:project_id' => 'projects#reject_shift_change'

  get '/reset_timesheet/:customer_id' => 'users#reset'
  post '/reset_timesheet/:customer_id' => 'users#reset'
  get 'approved_week' => 'users#approved_week'
  post 'approved_week' => 'users#approved_week'
  get 'default_week' => 'users#default_week'

  post 'customers/questionaire' => 'customers#questionaire'
  get 'assign_report_logo_to_user' => "users#assign_report_logo_to_user"
  get 'manage_profiles' => "users#manage_profiles"
  get 'assign_project' => "users#assign_project"
  post "invite_sub_users" => "users#invite_sub_users"
  get "login_user/:id" => "users#login_user"

  get 'user_profile' => "users#user_profile"
  get 'employee_profile' => "customers#employee_profile", as: :employee_profile
  get 'user_notification' => "users#user_notification", as: :user_notification
  get 'get_notification' => "users#get_notification"
  get 'available_tasks/:id' => 'tasks#available_tasks'
  get 'available_data/:id' => 'features#available_data'
  get 'available_users/:project_id' => 'customers#available_users'
  get '/default_comment' => 'tasks#default_comment'
  
  get 'check_holidays/:id' => "holidays#check_holidays"
  post 'holidays/create' => 'holidays#create'

  get 'inventory_reports/:id' => 'customers#inventory_reports'
  get 'customers/:id/customer_reports' => 'customers#customer_reports'
  get 'customers/:id/project_reports' => 'customers#project_reports'

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home

  end

  def about
    @about = Feature.find(9)
  end

  def features
    @feature_2 = Feature.find(2)
    @feature_3 = Feature.find(3)
    @feature_4 = Feature.find(4)
  end

  def privacy

  end

  def terms_of_service

  end

  def contact_form_mail
    respond_to do |format|
      if FeedbackMailer.contact_form_email(params[:email], params[:name], params[:message]).deliver
        format.html { flash[:notice] = "Email Sent!" }
        format.js { redirect_to root_path }
      else
        format.html { flash[:notice] = "Something Went Wrong, Our Developers Have Been Notified." }
        format.js { redirect_to root_path }
      end
    end
  end

end 

app/views/static_pages/_login_form.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="max-width: 380px; padding:0px;">
      <div class="modal-header" style="background-color: DodgerBlue;">
        <h5 style="background-color: DodgerBlue; color: white;" class="modal-title" id="loginModalLabel">LOGIN</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <%= f.input :email, label: false, required: false, autofocus: true, input_html: {class: 'form-control'} %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <%= f.input :password, label: false, required: false, input_html: {class: 'form-control'} %>
          </div>
          <div class="form-check form-check-inline">
            
            <%= f.input :remember_me, label: false, as: :boolean, class: "form-check-input" %>
            <label class="" style="margin-left: 10px;" for="exampleCheck1">Remember Me</label>
          </div>
          <div class="form-group">
            <%= f.button :submit, "Log in", style:"background-color: DodgerBlue;"%>
          </div>
        <% end %>
        <% User.omniauth_providers.each do |provider| %>
    
          <%= link_to user_google_oauth2_omniauth_authorize_path, class: "google-button" do %>
            <img src="/assets/g-normal.png"> Sign in with <%= OmniAuth::Utils.camelize(provider) %>
          <% end %><br />
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Forgot your password?", new_password_path(:user) %><br />
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#login_modal').click(function(){
    $('#loginModal').modal('show');

  });
</script>

app/views/static_pages/about.html.slim
div.grid-x style="width:100%;"
  div.about-div
  div(data-border-width="3" id="front-div-underline" class="col-md-10")
  div class="about-banner-text col-md-7" style="height: 150px; position: relative; margin-top: -130px;"
    p class="inside-image-banner"
      | Why
      span.orange-text
        |  Resource Stack, Inc.
      | ?

    div data-border-width="3" id="text-partial-underline" class="col-md-5"
  div.main_div
    p == @about.feature_data.html_safe if @about.feature_data.present?

.front-row.full-width.footer[style="height:200px; margin-top: 80px"]
  .footer_section
    .icons[style="width:100%; margin: 0;"]
      a[href="https://www.linkedin.com/company/1188919/" target="_blank" style="padding: 10px; float:left; margin-left: 25px;"]
        = image_tag("linkedin.png", style: 'background-color: white; border-radius: 7px;')
      a[href="https://www.facebook.com/Resource-Stack-Inc-269978683036453/" target="_blank" style="padding: 10px;float:left"]
        = image_tag("facebook.png", style: 'background-color: white; border-radius: 7px;')
      a[href="https://play.google.com/store/apps/details?id=com.resourcestack.chronstack" target="_blank" style="/* padding: 10px; */float: right;margin-right: 40px;margin-left: 20px;margin-top: -1px;"]
        = image_tag("google.png", style: "width:150px;margin-top: 12px;")
      a[href="https://apps.apple.com/app/id1514665138" target="_blank" style="float: right;"]
        = image_tag("apple_store.png", style: "width:150px;")
  .row.top-of-footer
    .col-md-5[style="margin-left: auto;margin-right: auto;"]
      .col-md-6[style="color: white; font-weight: bold; height:125px; font-size: 14px; text-align: right; float:left; padding:10px 15px; margin-top: -80px;"]
        | Resource Stack, INC.
        br
        | 626 Grant Street Suite D
        br
        | Herndon, VA 20170
      .col-md-6.address[style="color: white; height:80px; font-weight: bold;float:right;margin-top: -70px;"]
        p[style="text-align:left;"]
          | info@resourcestack.com
        p[style="color:white;text-align: left;"]
          | 571-223-6741
  p[style="color: white; text-align:center;font-weight: bold;"]
    | © 2017 Resource Stack, Inc. All Rights Reserved.

== render partial: 'static_pages/login_form'

app/views/static_pages/features.html.erb
<div class="container-fluid">
  <div class="row front-row">
    <div id="features-div">
      <div class="image-banner-text col-md-8" style="height: 150px; top: 57%; position: relative;">
        <p class="inside-image-banner">Efficient and Flexible Time Entry
        </p>

        <div data-border-width="3" id="text-partial-underline" class="col-md-5"></div>
        <div id="under-image-banner-text" class="col-md-7">
        </div>
      </div>
    </div>
    <div data-border-width="3" id="front-div-underline" class="col-md-10"></div>

  </div>
  <div class="row text-row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= @feature_2.feature_data.html_safe if @feature_2 && @feature_2.feature_data.present? %></div>
    <div class="col-md-2"></div>
  </div>

  <div class="row front-row">
    <div id="features-div-2">
      <div class="image-banner-text col-md-7" style="height: 150px; top: 57%; position: relative;">
        <p class="inside-image-banner">Easy Submission and Approval
        </p>

        <div data-border-width="3" id="text-partial-underline" class="col-md-5"></div>
        <div id="under-image-banner-text" class="col-md-7">
        </div>
      </div>
    </div>
    <div data-border-width="3" id="front-div-underline" class="col-md-10"></div>


  </div>
  <div class="row text-row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= @feature_3.feature_data.html_safe if @feature_3 && @feature_3.feature_data.present? %></div>
    <div class="col-md-2"></div>
  </div>

  <div class="row front-row">
    <div id="features-div-3">
      <div class="image-banner-text col-md-7" style="height: 150px; top: 57%; position: relative;">
        <p class="inside-image-banner">Flexible Reports
        </p>

        <div data-border-width="3" id="text-partial-underline" class="col-md-5" style="float: right;"></div>
        <div id="under-image-banner-text" class="col-md-7">
        </div>
      </div>
    </div>
    <div data-border-width="3" id="front-div-underline" class="col-md-10"></div>


  </div>
  <div class="row text-row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= @feature_4.feature_data.html_safe if @feature_4 && @feature_4.feature_data.present? %></div>
    <div class="col-md-2"></div>
  </div>

  <div class="front-row full-width footer" style="height:200px; margin-top: 80px">
    <div class="footer_section">
      <div class="icons" style="width:100%; margin: 0;">
        <a href="https://www.linkedin.com/company/1188919/" target="_blank" style="padding: 10px; float:left; margin-left: 25px;"><%= image_tag("linkedin.png", style: 'background-color: white; border-radius: 7px;') %></a>
        <a href="https://www.facebook.com/Resource-Stack-Inc-269978683036453/" target="_blank" style="padding: 10px;float:left"><%= image_tag("facebook.png", style: 'background-color: white; border-radius: 7px;') %></a>
        <a href="https://play.google.com/store/apps/details?id=com.resourcestack.chronstack" target="_blank" style="/* padding: 10px; */float: right;margin-right: 40px;margin-left: 20px;margin-top: -1px;"><%= image_tag("google.png", style: "width:150px;margin-top: 12px;") %></a>
        <a href="https://apps.apple.com/app/id1514665138" target="_blank" style="float: right;"><%= image_tag("apple_store.png", style: "width:150px;") %></a>
      </div>
    </div>
    <div class="row top-of-footer">
      <div class="col-md-5" style="margin-left: auto;margin-right: auto;">
        <div class="col-md-6" style="color: white; font-weight: bold; height:125px; font-size: 14px; text-align: right; float:left; padding:10px 15px; margin-top: -80px;">
          Resource Stack, INC.</br>626 Grant Street Suite D</br>Herndon, VA 20170
        </div>
        <div class="col-md-6 address" style="color: white; height:80px; font-weight: bold;float:right;margin-top: -70px;">
          <p style="text-align:left;">info@resourcestack.com</p>
          <p style="color:white;text-align: left;">571-223-6741</p>
        </div>
      </div>
    </div>
    <p style="color: white; text-align:center;font-weight: bold;">&copy; 2017 Resource Stack, Inc. All Rights Reserved.</p>
  </div>
</div>

<%= render partial: 'static_pages/login_form'%>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <div class="row front-row">
    <div class="front_div">

    </div>
    <div data-border-width="3" id="front-div-underline" class="col-md-10"></div>
    <div class="image-banner-text col-md-7" id="front-page-banner-text" style="position: relative; top: 0%; margin-top: -170px;">
      <p class="inside-image-banner">A Time Tracking Solution<br>
        For Your Business
      </p>

      <div data-border-width="3" id="text-partial-underline" class="col-md-5"></div>
      <div id="under-image-banner-text" class="col-md-7">Independent of an employee's location,
        stay organized and capture every billing hour with our cloud based application.
        Deploy in minutes and accelerate your efficiency by light years.
      </div>
    </div>

  </div>

  <div class="row sub-heading">

  </div>

  <div class="row" id="gray-bar">
    <h2 class="col-md-12 aboutus"><span class="about">ABOUT</span><span class="us">US</span></h2>
    <br>
    <div class="col-md-1"></div>
    <div class="col-md-10" id="gray-paragraph">Early-stage consulting firms and other small business with fewer than 50 employees often
      resort to manual time entry to track their employees’ work. ChronStack enables employers to
      automate and streamline the time-entry and reporting process. The cloud-based platform
      developed by ResouceStack, Inc. is simple to deploy for business owners and easy for their
      employees to use. While ChronStack is feature rich, it is designed for small companies with
      limited budgets who don’t need enterprise-scale software.</div>
    <div class="col-md-1"></div>
  </div>

  <%= render partial: 'static_pages/login_form'%>
  <!-- <div id ="player"></div> -->

  <!-- TOP SQUARE ROW -->
  <div class="row" id="top-square-row">

      <a class="col-md-3 info-square" href="/features#features-div" style="background-image: linear-gradient(rgba(255, 223, 196, 0.35), rgba(123, 231, 216, 0.35)); margin-left:auto; margin-right: auto;">
        <img class="icon" src="assets/stopwatch.png">
        <div class="square-header">Simplified Time-Tracking</div>
        <div class="square-list">
          <ul>
            <li>Fully automated platform</li>
            <li>Easier and efficient entries</li>
            <li>Supports custom time-sheet inputs</li>
          </ul>
        </div>
      </a>

  </div>
  <!-- MIDDLE SQUARE ROW -->
  <div class="row" id="middle-square-row">
    <div class="col-md-10 row" style="margin-left:auto; margin-right: auto;">
      <div class="col-md-4">
        <a class="info-square" href="/features#features-div-3" style="background-image: linear-gradient(rgba(123, 231, 216, 0.35), rgba(0, 244, 210, 0.35));">
          <img class="icon" src="assets/wrench-gear.png">
          <div class="square-header">Configurable Management<br> Reports</div>
          <div class="square-list" style="margin-top:2%;">
            <ul>
              <li>Clear, well-formatted reports</li>
              <li>Manager’s can view time reporting according to their choice</li>
            </ul>
          </div>
        </a>
      </div>
      <div class="col-md-4">
        <div class="info-square middle-square">
          <div class="middle-square-header">
            <div class="ourservices"><div class="about">OUR</div> <div class="us">SERVICES</div></div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
          <a class="info-square" href="/features#features-div-2" style="background-image: linear-gradient(rgba(123, 231, 216, 0.35), rgba(0, 244, 210, 0.35));">
            <img class="icon" src="assets/double-arrow.png" style="top: 25%;">
            <div class="square-header">Flexible Time Entry System</div>
            <div class="square-list">
              <ul>
                <li>Cloud solutions for projects/employees</li>
                <li>Multiple entries under each day</li>
                <li>Add additional entries on later date</li>
              </ul>
            </div>
          </a>
      </div>
    </div>
  </div>
  <!-- BOTTOM SQUARE ROW -->
  <div class="row" id="bottom-square-row">

    <div class="col-md-3 info-square" style="background-image: linear-gradient(rgba(0, 244, 210, 0.35), rgb(0, 215, 179)); margin-left:auto; margin-right: auto;">
      <img class="icon" src="assets/green-email.png" style="right: 7%;top: 20%;">
      <div class="square-header">Email Notifications & Reminders</div>
      <div class="square-list">
        <ul>
          <li>Notifies the user about pending/missed time sheets</li>
        </ul>
      </div>
    </div>
  </div>

  <!--<div class="row" id="light-gray-bar">
    <h2 class="col-md-12 aboutus"><span class="about">TOP</span><span class="us">CLIENTS</span></h2>
    <br>
    <div class="col-md-1"></div>

    <div class="col-md-1"></div>
  </div>-->

  <br>

  <div data-border-width="3" id="above-contact-underline" class="col-md-10"></div>
  <div class="row" style="margin:0;">
    <p class="inside-image-banner contact-header">Contact Us
    </p>
    <div class="col-md-2"></div>
    <div class="col-md-8" id="contact-form">
      <%= form_tag '/contact_form_mail', method: :post, remote: true do %>
        <div class="row" style="width:100%;">
          <%= label_tag "name", "Name", class: 'col-md-6 contact-label' %>
          <%= label_tag "email", "Email", class: 'col-md-6 contact-label', style: 'padding-left: 7%;' %>
        </div>
        <div class="row contact-input-row">
          <div class="col-md-6">
            <%= text_field_tag :name, '', class: 'contact-input', style: 'float:left; margin-bottom: 10px;' %>
          </div>
          <div class="col-md-6">
            <%= text_field_tag :email, '', class: 'contact-input', style: 'float: right; margin-bottom: 10px;' %>
          </div>
        </div>
        <%= label_tag "message", "Message", class: 'contact-label' %>
        <div class="row contact-input-row">
          <div class="col-md-12">
            <%= text_area_tag :message, '', class: 'contact-input-area' %>
          </div>
        </div>
        <div class="row submit-button-row">
          <%= submit_tag 'Submit', id: 'contact-button' %>
          <%= flash[:notice] if flash[:notice] && !flash[:notice].include?("Signed") %>
        </div>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="front-row full-width footer" style="height:200px; margin-top: 80px">
    <div class="footer_section">
      <div class="icons" style="width:100%; margin: 0;">
        <a href="https://www.linkedin.com/company/1188919/" target="_blank" style="padding: 10px; float:left; margin-left: 25px;"><%= image_tag("linkedin.png", style: 'background-color: white; border-radius: 7px;') %></a>
        <a href="https://www.facebook.com/Resource-Stack-Inc-269978683036453/" target="_blank" style="padding: 10px;float:left"><%= image_tag("facebook.png", style: 'background-color: white; border-radius: 7px;') %></a>
        <a href="https://play.google.com/store/apps/details?id=com.resourcestack.chronstack" target="_blank" style="/* padding: 10px; */float: right;margin-right: 40px;margin-left: 20px;margin-top: -1px;"><%= image_tag("google.png", style: "width:150px;margin-top: 12px;") %></a>
        <a href="https://apps.apple.com/app/id1514665138" target="_blank" style="float: right;"><%= image_tag("apple_store.png", style: "width:150px;") %></a>
      </div>
    </div>
    <div class="row top-of-footer">
      <div class="col-md-5" style="margin-left: auto;margin-right: auto;">
        <div class="col-md-6" style="color: white; font-weight: bold; height:125px; font-size: 14px; text-align: right; float:left; padding:10px 15px; margin-top: -80px;">
          Resource Stack, INC.</br>626 Grant Street Suite D</br>Herndon, VA 20170
        </div>
        <div class="col-md-6 address" style="color: white; height:80px; font-weight: bold;float:right;margin-top: -70px;">
          <p style="text-align:left;">info@resourcestack.com</p>
          <p style="color:white;text-align: left;">571-223-6741</p>
        </div>
      </div>
    </div>
    <p style="color: white; text-align:center;font-weight: bold;">&copy; 2017 Resource Stack, Inc. All Rights Reserved.</p>
  </div>
</div>
<script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '500',
          width: '100%',
          videoId: 'P0FDBYw8R3Y',
          playerVars: {rel:0, showinfo:0},
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>