config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :archived_time_entries, only: [:index, :show, :create]
  resources :archived_weeks, only: [:index, :show, :create]
  resources :holiday_exceptions
  resources :time_entries
  resources :weeks 
  resources :tasks
  resources :projects
  resources :customers
  resources :roles
  resources :users
  resources :holidays
  resources :employment_types
  resources :customers_holidays
  resources :report_logos
  resources :features, except: [:index]
  resources :case_studies
  resources :vacation_types
  resources :shifts
  resources :project_shifts
  resources :announcements
  devise_for :users, :path => "account", :controllers => { passwords: 'passwords', registrations: 'registrations', invitations: 'invitations', :omniauth_callbacks => "users/omniauth_callbacks", :sessions => 'sessions' }
  devise_scope :user do
    match "/users/sign_in", :to => 'devise/sessions#new', via: [:get, :post]
    match "/users/sign_out", :to => 'devise/sessions#destroy', via: [:delete]
    match '/invitation/resend_invite' => 'invitations#resend_invite', via: [:post]
  end

  post '/weeks/:id(.:format)' => 'weeks#update'
  authenticated :user do
    root to: 'weeks#index', as: :authenticated_root
  end
  
  get "/get_user_projects" => "users#get_user_projects"
  post '/application_versions/get_items' => "application_versions#get_items"
  get '/application_versions/delete_item' => "application_versions#delete_item" 
  post '/application_versions/edit_item' => "application_versions#edit_item"
  get '/application_versions/acknowledge_version' => "application_versions#acknowledge_version" 

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/features' => 'static_pages#features'
  namespace :api do
    post 'social_login', to: "users#social_login"
    post 'login_user', to: "users#login_user"
    get 'login_user', to: "users#login_user"
    get 'get_weekly_time_entries', to: "time_entries#get_weekly_time_entries"
    get 'get_daily_time_entries', to: "time_entries#get_daily_time_entries"
    get 'submit_weekly_time_entry', to: "time_entries#submit_weekly_time_entry"
    get 'delete_time_entry', to: "time_entries#delete_time_entry"
    get 'get_time_entry_detail', to: "time_entries#get_time_entry_detail"
    post 'save_time_entry', to: "time_entries#save_time_entry"
    get 'get_user_projects', to: "time_entries#get_user_projects"
    get 'get_project_tasks', to: "time_entries#get_project_tasks"
    post 'save_device_info', to: "notifications#save_device_info"
    get 'remove_device_info', to: "notifications#remove_device_info"
    get 'get_customer_detail', to: "users#get_customer_detail"
    get 'get_customer_holidays', to: "users#get_customer_holidays"
    get 'agree_to_terms_and_conditions', to: "users#agree_to_terms_and_conditions"

    post 'send_entry', to: "users#post_data"
    get 'send_entry', to: "users#post_data"

    get 'get_time_entry', to: "users#get_time_entry"
    post 'get_time_entry', to: "users#get_time_entry"

    get 'get_tasks', to: "users#get_tasks"
    post 'get_tasks', to: "users#get_tasks"

    post 'update_date', to: "users#update_date"
    get 'update_date', to: "users#update_date"

    post 'get_submitted_timesheet', to: "users#get_submitted_timesheet"
    get 'get_submitted_timesheet', to: "users#get_submitted_timesheet"

    post 'approve', to: "users#approve"
    get 'approve', to: "users#approve"

    post 'reject', to: "users#reject"
    get 'reject', to: "users#reject"

    post 'submit_week', to: "users#submit_week"

    resource :sessions, only: [:create, :destroy]
  end

  post 'change_status' => 'weeks#change_status', as: :change_status
  get 'duplicate' => 'weeks#duplicate'
  get 'weeks/:id/report' => 'weeks#report'
  
  get '/dynamic_project_update' => 'projects#dynamic_project_update'
  get '/dynamic_customer_update' => 'customers#dynamic_customer_update'
  post '/add_configuration' => 'customers#add_configuration', as: :add_configuration
  get '/remove_configuration' => 'customers#remove_configuration', as: :remove_configuration

  post '/create_project_from_system' => 'projects#create_project_from_system'
  get 'show_projects/:system' => 'projects#show_projects'

  get 'projects/:id/approve/:week_id/:row_id' => 'projects#approve'
  match 'weeks/dismiss/:week_id/:row_id' => 'weeks#dismiss', via: [:get, :post]
  get 'projects/:id/reject/:week_id' => 'projects#reject'
  get 'show_project_reports' => 'projects#show_project_reports'
  post 'add_multiple_users_to_project' => "projects#add_multiple_users_to_project"
  post 'remove_multiple_users_from_project' => "projects#remove_multiple_users_from_project"
  post 'shift_modal' => "projects#shift_modal"
  get 'show_shift_reports' => "shifts#show_shift_reports"
  get 'cm_shift_report' => "shifts#cm_shift_report"
  get 'shift_report/:id' => "shifts#shift_report"
  post 'shift_report/:id' => "shifts#shift_report"
  post 'show_project_reports' => 'projects#show_project_reports'
  post 'projects/:id/deactivate_project' => 'projects#deactivate_project'
  post 'projects/:id/reactivate_project' => 'projects#reactivate_project'
  post 'time_reject' => 'weeks#time_reject'
  post 'show_hours' => 'projects#show_hours'
  post '/pending_email' => 'projects#pending_email'
  post '/customers_pending_email' => 'customers#customers_pending_email'
  post '/previous_comments' => 'weeks#previous_comments'
  post '/shared_user' => 'customers#shared_user'
  get '/add_shared_users' => 'customers#add_shared_users'
  post '/assign_shift' => 'shifts#assign_shift'
  get '/toggle_shift' => 'shifts#toggle_shift'
  post '/add_previous_week' => 'weeks#add_previous_week', as: :add_previous_week
  post '/open_previous_week_modal' => 'weeks#open_previous_week_modal'

  post '/open_edit_customer_modal' => 'customers#open_edit_customer_modal'

  post '/hours_approved' => 'customers#hours_approved', as: :hours_approved
  post '/hours_submitted' => 'customers#hours_submitted', as: :hours_submitted
  get '/users_on_project' => 'customers#users_on_project', as: :users_on_project
  get '/show_pm_projects' => 'customers#show_pm_projects', as: :show_pm_projects

  get '/show_user_reports/:id' => 'users#show_user_reports'
  post '/show_user_reports/:id' => 'users#show_user_reports'

  get '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'
  post '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'

  get '/set_default_project' => 'users#set_default_project'
  post '/update_announcement' => 'announcements#update_announcement'

  match 'accept_terms_and_condition' => 'users#accept_terms_and_condition', via: [:get, :post]
  
  get 'add_user_to_project' => "projects#add_user_to_project"
  get '/projects/:id/user_time_report' => 'projects#user_time_report'
  match 'user_account', :to => "users#user_account",  via: [:get, :post]
  match 'admin', :to => "users#admin", via: [:get, :post]
  post 'update_front_page_content' => "features#update_front_page_content"
  get 'display_data' => "users#display_data"
  get 'remove_user_from_customer' => "customers#remove_user_from_customer"
  get 'shared_user' => "customers#shared_user"
  get 'add_pm_role' => "customers#add_pm_role"
  get 'assign_proxy_role' => "customers#assign_proxy_role"
  get 'assign_cm_proxy_role' => "customers#assign_cm_proxy_role"
  get 'edit_customer_user/:user_id' => "customers#edit_customer_user"
  get '/update_user_employment' => "customers#update_user_employment"
  get 'vacation_request' => "customers#vacation_request"
  post 'vacation_request' => "customers#vacation_request"
  get 'customers/approve_vacation/:vr_id/:row_id' => 'customers#approve_vacation'
  get 'customers/reject_vacation/:vr_id/:row_id' => 'customers#reject_vacation'
  get 'customers/approve_cancel_request/:vr_id/:row_id' => 'customers#approve_cancel_request'
  get 'resend_vacation_request' => 'customers#resend_vacation_request'
  get 'cancel_vacation_request' => 'customers#cancel_vacation_request' 
  get 'customers/:id/theme' => 'customers#set_theme'
  get 'customers/:id/clear_filter' => 'customers#clear_filter', as: :clear_filter
  get 'pre_vacation_request' => "customers#pre_vacation_request"
  get 'single_vacation_request' => "weeks#single_vacation_request"

  get 'shift_change_request' => "customers#shift_change_request"
  get 'shift_request' => 'customers#shift_request'
  get 'projects/approve_shift_change/:sr_id/:row_id/:project_id' => 'projects#approve_shift_change'
  get 'projects/reject_shift_change/:sr_id/:row_id/:project_id' => 'projects#reject_shift_change'

  get '/reset_timesheet/:customer_id' => 'users#reset'
  post '/reset_timesheet/:customer_id' => 'users#reset'
  get 'approved_week' => 'users#approved_week'
  post 'approved_week' => 'users#approved_week'
  get 'default_week' => 'users#default_week'

  post 'customers/questionaire' => 'customers#questionaire'
  get 'assign_report_logo_to_user' => "users#assign_report_logo_to_user"
  get 'manage_profiles' => "users#manage_profiles"
  get 'assign_project' => "users#assign_project"
  post "invite_sub_users" => "users#invite_sub_users"
  get "login_user/:id" => "users#login_user"

  get 'user_profile' => "users#user_profile"
  get 'employee_profile' => "customers#employee_profile", as: :employee_profile
  get 'user_notification' => "users#user_notification", as: :user_notification
  get 'get_notification' => "users#get_notification"
  get 'available_tasks/:id' => 'tasks#available_tasks'
  get 'available_data/:id' => 'features#available_data'
  get 'available_users/:project_id' => 'customers#available_users'
  get '/default_comment' => 'tasks#default_comment'
  
  get 'check_holidays/:id' => "holidays#check_holidays"
  post 'holidays/create' => 'holidays#create'

  get 'inventory_reports/:id' => 'customers#inventory_reports'
  get 'customers/:id/customer_reports' => 'customers#customer_reports'
  get 'customers/:id/project_reports' => 'customers#project_reports'

app/models/announcement.rb
class Announcement < ApplicationRecord
 
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_announcement, only: [:edit, :update_announcement, :destroy]

  def index
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    if params[:announcement_id].present?
      @announcement = Announcement.find_by_id params[:announcement_id]
    else
      @announcement = Announcement.new
    end
    @announcement.announcement_type = params[:announcement_type]
    @announcement.announcement_text = params[:text_content]   
    @announcement.active =params[:active]    
    @announcement.seen = false
    @announcement.save
    redirect_to  "/admin#announcementPanel"
    # respond_to do |format|
    #   format.js
    # end
  end

   def destroy    
    @announcement.destroy
    redirect_to admin_path
  end

  def update_announcement
    @user_announcement = UserAnnouncement.where(user_id: current_user.id, announcement_id: @announcement.id).last
    unless @user_announcement.present?
      UserAnnouncement.create!(user_id: current_user.id, announcement_id: @announcement.id)
    end
  end


  private
  
  def set_announcement
    @announcement = Announcement.find_by_id(params[:id])
  end
  
end

app/views/announcements/_new_announcement.html.slim
div(id="newAnnouncement" class="modal" aria-hidden="true" role="dialog" data-reveal data-close-on-esc="false")
	div class="modal-dialog" role="document"
	  div.modal-content style="width: 800px !important;left:-135px;"
	    div.modal-header
	      h5 class="modal-title" Latest Announcement	      
	      button.close type="button" aria8-label="Close" data-dismiss="modal"  id= "#{@announcement.id}" class="announce_popup"
	          span aria-hidden="true"  &times;
	    div.modal-body
				
			h5 class="modal-title" = @announcement.announcement_type
						
			div (style= "width:720px;height: 300px;overflow-y:scroll;padding:15px;") = @announcement.announcement_text.html_safe 
						
			= link_to "Ok", "javascript:void(0);", id: "#{@announcement.id}" ,class: "announce_popup orange-button"
					

							
coffee:
	$(document).ready ->
		$('#newAnnouncement').modal('show');
	

app/views/announcements/_open_announcement_modal.html.slim
div class="modal fade" id="announcemntModal" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal-dialog" role="document"
   div class="modal-content" style="left:-240px;"
     div class="modal-header" style="padding:0px;"
       h1 Create Announcements 
       button type="button" class="close" data-dismiss="modal" aria-label="Close"
         span aria-hidden="true" &times;
         
    
     div class="modal-body"
		span class="announcement_message" style="color: green;"
		= form_tag announcements_path, id: "announcement_page_content", method: :post, remote: true
			-if @announcement.present?
				= hidden_field_tag 'announcement_id', @announcement.id
			table			
				tr
					td	Title
					td = text_field_tag :announcement_type, (@announcement.present? && @announcement.announcement_type.present?) ? @announcement.announcement_type : "", placeholder: "Announcement Type", required: "required", style:'width:850px', class:'form-control'				
				tr
					td Active					
					td = check_box_tag :active, true, (@announcement.present?)? @announcement.active? : true
				tr
					td	Content					
					td = cktext_area_tag :text_content, (@announcement.present? && @announcement.announcement_text.present?) ? @announcement.announcement_text.html_safe : "" ,cols:38 
				tr
					td = submit_tag "Submit"

	
					

app/views/announcements/create.js.erb
$('.announcement_message').html("<%= j flash.now[:notice] = "Announcement has been updates sucessfully" %>");
$('#announcemntModal').modal("hide");

app/views/announcements/create_announcement.js.erb
$('.announcement_message').html("<%= j flash.now[:notice] = "Announcement has been updates sucessfully" %>");
$('#announcemntModal').modal("hide");

app/views/announcements/edit.js.erb
$('#announcements_reload').html("<%= j render partial: 'announcements/open_announcement_modal' %>");

$('#announcemntModal').modal("show");

        

app/views/announcements/edit_announcement.js.erb
$('#announcements_reload').html("<%= j render partial: 'announcements/open_announcement_modal' %>");
$('#announcemntModal').modal("show");
CKEDITOR.instances.text_content_content.setData('<%=@announcement.announcement_text %>');
        

app/views/announcements/update_announcement.js.erb
$('#newAnnouncement').modal("hide");