config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :archived_time_entries, only: [:index, :show, :create]
  resources :archived_weeks, only: [:index, :show, :create]
  resources :holiday_exceptions
  resources :time_entries
  resources :weeks 
  resources :tasks
  resources :projects
  resources :customers
  resources :roles
  resources :users
  resources :holidays
  resources :employment_types
  resources :customers_holidays
  resources :report_logos
  resources :features, except: [:index]
  resources :case_studies
  resources :vacation_types
  resources :shifts
  resources :project_shifts
  resources :announcements
  devise_for :users, :path => "account", :controllers => { passwords: 'passwords', registrations: 'registrations', invitations: 'invitations', :omniauth_callbacks => "users/omniauth_callbacks", :sessions => 'sessions' }
  devise_scope :user do
    match "/users/sign_in", :to => 'devise/sessions#new', via: [:get, :post]
    match "/users/sign_out", :to => 'devise/sessions#destroy', via: [:delete]
    match '/invitation/resend_invite' => 'invitations#resend_invite', via: [:post]
  end

  post '/weeks/:id(.:format)' => 'weeks#update'
  authenticated :user do
    root to: 'weeks#index', as: :authenticated_root
  end
  
  get "/get_user_projects" => "users#get_user_projects"
  post '/application_versions/get_items' => "application_versions#get_items"
  get '/application_versions/delete_item' => "application_versions#delete_item" 
  post '/application_versions/edit_item' => "application_versions#edit_item"
  get '/application_versions/acknowledge_version' => "application_versions#acknowledge_version" 

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/features' => 'static_pages#features'
  namespace :api do
    post 'social_login', to: "users#social_login"
    post 'login_user', to: "users#login_user"
    get 'login_user', to: "users#login_user"
    get 'get_weekly_time_entries', to: "time_entries#get_weekly_time_entries"
    get 'get_daily_time_entries', to: "time_entries#get_daily_time_entries"
    get 'submit_weekly_time_entry', to: "time_entries#submit_weekly_time_entry"
    get 'delete_time_entry', to: "time_entries#delete_time_entry"
    get 'get_time_entry_detail', to: "time_entries#get_time_entry_detail"
    post 'save_time_entry', to: "time_entries#save_time_entry"
    get 'get_user_projects', to: "time_entries#get_user_projects"
    get 'get_project_tasks', to: "time_entries#get_project_tasks"
    post 'save_device_info', to: "notifications#save_device_info"
    get 'remove_device_info', to: "notifications#remove_device_info"
    get 'get_customer_detail', to: "users#get_customer_detail"
    get 'get_customer_holidays', to: "users#get_customer_holidays"
    get 'agree_to_terms_and_conditions', to: "users#agree_to_terms_and_conditions"

    post 'send_entry', to: "users#post_data"
    get 'send_entry', to: "users#post_data"

    get 'get_time_entry', to: "users#get_time_entry"
    post 'get_time_entry', to: "users#get_time_entry"

    get 'get_tasks', to: "users#get_tasks"
    post 'get_tasks', to: "users#get_tasks"

    post 'update_date', to: "users#update_date"
    get 'update_date', to: "users#update_date"

    post 'get_submitted_timesheet', to: "users#get_submitted_timesheet"
    get 'get_submitted_timesheet', to: "users#get_submitted_timesheet"

    post 'approve', to: "users#approve"
    get 'approve', to: "users#approve"

    post 'reject', to: "users#reject"
    get 'reject', to: "users#reject"

    post 'submit_week', to: "users#submit_week"

    resource :sessions, only: [:create, :destroy]
  end

  post 'change_status' => 'weeks#change_status', as: :change_status
  get 'duplicate' => 'weeks#duplicate'
  get 'weeks/:id/report' => 'weeks#report'
  
  get '/dynamic_project_update' => 'projects#dynamic_project_update'
  get '/dynamic_customer_update' => 'customers#dynamic_customer_update'
  post '/add_configuration' => 'customers#add_configuration', as: :add_configuration
  get '/remove_configuration' => 'customers#remove_configuration', as: :remove_configuration

  post '/create_project_from_system' => 'projects#create_project_from_system'
  get 'show_projects/:system' => 'projects#show_projects'

  get 'projects/:id/approve/:week_id/:row_id' => 'projects#approve'
  match 'weeks/dismiss/:week_id/:row_id' => 'weeks#dismiss', via: [:get, :post]
  get 'projects/:id/reject/:week_id' => 'projects#reject'
  get 'show_project_reports' => 'projects#show_project_reports'
  post 'add_multiple_users_to_project' => "projects#add_multiple_users_to_project"
  post 'remove_multiple_users_from_project' => "projects#remove_multiple_users_from_project"
  post 'shift_modal' => "projects#shift_modal"
  get 'show_shift_reports' => "shifts#show_shift_reports"
  get 'cm_shift_report' => "shifts#cm_shift_report"
  get 'shift_report/:id' => "shifts#shift_report"
  post 'shift_report/:id' => "shifts#shift_report"
  post 'show_project_reports' => 'projects#show_project_reports'
  post 'projects/:id/deactivate_project' => 'projects#deactivate_project'
  post 'projects/:id/reactivate_project' => 'projects#reactivate_project'
  post 'time_reject' => 'weeks#time_reject'
  post 'show_hours' => 'projects#show_hours'
  post '/pending_email' => 'projects#pending_email'
  post '/customers_pending_email' => 'customers#customers_pending_email'
  post '/previous_comments' => 'weeks#previous_comments'
  post '/shared_user' => 'customers#shared_user'
  get '/add_shared_users' => 'customers#add_shared_users'
  post '/assign_shift' => 'shifts#assign_shift'
  get '/toggle_shift' => 'shifts#toggle_shift'
  post '/add_previous_week' => 'weeks#add_previous_week', as: :add_previous_week
  post '/open_previous_week_modal' => 'weeks#open_previous_week_modal'

  post '/open_edit_customer_modal' => 'customers#open_edit_customer_modal'

  post '/hours_approved' => 'customers#hours_approved', as: :hours_approved
  post '/hours_submitted' => 'customers#hours_submitted', as: :hours_submitted
  get '/users_on_project' => 'customers#users_on_project', as: :users_on_project
  get '/show_pm_projects' => 'customers#show_pm_projects', as: :show_pm_projects

  get '/show_user_reports/:id' => 'users#show_user_reports'
  post '/show_user_reports/:id' => 'users#show_user_reports'

  get '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'
  post '/show_user_weekly_reports/:id' => 'users#show_user_weekly_reports'

  get '/set_default_project' => 'users#set_default_project'
  post '/update_announcement' => 'announcements#update_announcement'

  match 'accept_terms_and_condition' => 'users#accept_terms_and_condition', via: [:get, :post]
  
  get 'add_user_to_project' => "projects#add_user_to_project"
  get '/projects/:id/user_time_report' => 'projects#user_time_report'
  match 'user_account', :to => "users#user_account",  via: [:get, :post]
  match 'admin', :to => "users#admin", via: [:get, :post]
  post 'update_front_page_content' => "features#update_front_page_content"
  get 'display_data' => "users#display_data"
  get 'remove_user_from_customer' => "customers#remove_user_from_customer"
  get 'shared_user' => "customers#shared_user"
  get 'add_pm_role' => "customers#add_pm_role"
  get 'assign_proxy_role' => "customers#assign_proxy_role"
  get 'assign_cm_proxy_role' => "customers#assign_cm_proxy_role"
  get 'edit_customer_user/:user_id' => "customers#edit_customer_user"
  get '/update_user_employment' => "customers#update_user_employment"
  get 'vacation_request' => "customers#vacation_request"
  post 'vacation_request' => "customers#vacation_request"
  get 'customers/approve_vacation/:vr_id/:row_id' => 'customers#approve_vacation'
  get 'customers/reject_vacation/:vr_id/:row_id' => 'customers#reject_vacation'
  get 'customers/approve_cancel_request/:vr_id/:row_id' => 'customers#approve_cancel_request'
  get 'resend_vacation_request' => 'customers#resend_vacation_request'
  get 'cancel_vacation_request' => 'customers#cancel_vacation_request' 
  get 'customers/:id/theme' => 'customers#set_theme'
  get 'customers/:id/clear_filter' => 'customers#clear_filter', as: :clear_filter
  get 'pre_vacation_request' => "customers#pre_vacation_request"
  get 'single_vacation_request' => "weeks#single_vacation_request"

  get 'shift_change_request' => "customers#shift_change_request"
  get 'shift_request' => 'customers#shift_request'
  get 'projects/approve_shift_change/:sr_id/:row_id/:project_id' => 'projects#approve_shift_change'
  get 'projects/reject_shift_change/:sr_id/:row_id/:project_id' => 'projects#reject_shift_change'

  get '/reset_timesheet/:customer_id' => 'users#reset'
  post '/reset_timesheet/:customer_id' => 'users#reset'
  get 'approved_week' => 'users#approved_week'
  post 'approved_week' => 'users#approved_week'
  get 'default_week' => 'users#default_week'

  post 'customers/questionaire' => 'customers#questionaire'
  get 'assign_report_logo_to_user' => "users#assign_report_logo_to_user"
  get 'manage_profiles' => "users#manage_profiles"
  get 'assign_project' => "users#assign_project"
  post "invite_sub_users" => "users#invite_sub_users"
  get "login_user/:id" => "users#login_user"

  get 'user_profile' => "users#user_profile"
  get 'employee_profile' => "customers#employee_profile", as: :employee_profile
  get 'user_notification' => "users#user_notification", as: :user_notification
  get 'get_notification' => "users#get_notification"
  get 'available_tasks/:id' => 'tasks#available_tasks'
  get 'available_data/:id' => 'features#available_data'
  get 'available_users/:project_id' => 'customers#available_users'
  get '/default_comment' => 'tasks#default_comment'
  
  get 'check_holidays/:id' => "holidays#check_holidays"
  post 'holidays/create' => 'holidays#create'

  get 'inventory_reports/:id' => 'customers#inventory_reports'
  get 'customers/:id/customer_reports' => 'customers#customer_reports'
  get 'customers/:id/project_reports' => 'customers#project_reports'

app/helpers/projects_helper.rb
module ProjectsHelper
  def consultant_name(fname, lname, email)
    consultant_name = email
    if fname.nil? || lname.nil?
  
    else
      consultant_name = "#{fname} #{lname}"
    end
    return consultant_name
  end
end

app/views/projects/_add_configuration.html.slim
h6 Configurate External Systems
h1 Projects
p By setting up and allowing Chronstack your specific external systems credential. 
p This will allow projects to automatically populate and be modified within both.
h6 New Configuration Setup

=form_tag add_configuration_path, id: "add_configuration_form", method: :post, remote: true

	table.configuration_table
		tr.dark_row
			th External System
			th Email
		tr 

			td JIRA
			= hidden_field_tag :system_type, "Jira"
			td = text_field_tag :jira_email, '' , required: true
		tr.dark_row
			th API Token
			th External Url
		tr 
			td = text_field_tag :api_token, '', required: true	
			td = text_field_tag :url, '', required: true
			td = submit_tag 'Submit', id: 'check_password' , disabled: @current_systems.present? ? true : false

		tr.dark_row
			td  colspan= 3
				 a class="nav-link" id="apitoken_types-tab"  href='https://id.atlassian.com/manage-profile/security/api-tokens' target='_blank'  Please click here to generate the API token 


h6 Active External Systems

-if @current_systems.present?
	table
		tr.dark_row 
			th (style= "width: 25%;") External System
			th (style= "width: 25%;") External Url
			th (style= "width: 25%;") Username
			th (style= "width: 25%;") Action
		- @current_systems.each do |sys|
			tr
				td = sys.system_type
				td = sys.url
				td = sys.jira_email
				td = link_to 'Remove', remove_configuration_path(sys_id: sys.id), remote: true
- else
	p There are curreltly no active external systems that have been setup

h5 Accounting
h5 Other

app/views/projects/_adhoc_pm_form.html.slim
.left-row-adhoc
	h1 Adhoc Project Manager
	= form_tag add_adhoc_pm_path(params[:project_id]), id: "adhoc_pm_form", method: :post, remote: true
		table
			thead
				tr
					th User Email
					th Start Date
					th End Date
			
			tbody
				tr
					td
						= select_tag :adhoc_pm_id, options_from_collection_for_select(@project.users, "id", "email"), :include_blank => true, class:"form-control"
					td
						= text_field_tag 'adhoc_start_date', '',{required: "required",:placeholder =>  "yyyy/mm/dd", :style=>"font-size: 12.5px;", class:" datepicker form-control"}
					td
						= text_field_tag 'adhoc_end_date', '',  {required: "required", :placeholder =>  "yyyy/mm/dd", :style=>"font-size: 12.5px;" , class: " datepicker form-control"}
				
		.actions = submit_tag 'Assign PM'
						
.right-row-adhoc
	h1 Assigned Adhoc PM
	table class="table"
		thead
			tr
				th User Email
				th Start Date
				th End Date

		- if @adhoc_pm.present?
			tbody
				tr
					td
						= @adhoc_pm.email
					td 
						= @project.adhoc_start_date.to_date
					td
						= @project.adhoc_end_date.to_date

div style="clear:both;"

coffee:
	$('.datepicker').datepicker({
    	autoclose: true,
    	format: "yyyy-mm-dd"

    })

app/views/projects/_holiday_exceptions_form.html.slim
h2.text-center Holidays Setup
br
br
- if @holidays.any?
	- if @holiday_exceptions.present?
		h4.text-center Holiday Exceptions
		- @holiday_exceptions.each do |h|
	  		.grid-x
 				.small-6.columns.text-center =("#{User.find(h.user_id).first_name} #{User.find(h.user_id).last_name}")
				.small-1.columns.text-center = h.holiday_ids.count
				.small-1.columns.text-center = link_to "Edit", edit_holiday_exception_path(h)
				.small-1.columns.text-center = link_to "Delete", holiday_exception_path(h), data: { confirm: 'Are you sure you want to delete holiday exception for this user?' }, method: :delete
				.small-1.columns

h4.text-center New Holiday Exception
= form_for @holiday_exception, remote: true do |f|
		= f.select :user_id, @project.users.collect { |m| [ m.first_name, m.id ] }, {include_blank: true}, {required: "required", class:"form-control"}
		= f.collection_check_boxes(:holiday_ids, @holidays.all, :id, :name, include_hidden: false) do |h|
		 .grid-x
			.small-6.cell.text-center = h.check_box
			.small-2.cell.text-center = h.object.name
			.small-2.cell.text-center = h.object.date.strftime("%m-%d-%y")
			.small-1.cell
		= f.hidden_field :customer_id, value: @customer.id
		= f.hidden_field :project_id, value: @project.id
		.actions = f.submit

app/views/projects/_new_edit_form.html.slim
== render 'form'
div[style="width: 90%; margin-left: 7%;"]
  - if @project.user_id == current_user.id || !user_have_adhoc_permission(current_user)
    span class="badge"
      = link_to 'Report', "/show_project_reports?id=#{@project.id}", :method => :get,class: "center orange-button large-3 cell", style: "margin: 5px;"
    span class="badge"
      = link_to 'Shift Report', "/show_shift_reports?id=#{@project.id}&type=project", :method => :get, class: "center orange-button large-3 cell", style: "margin: 5px;"
  - if user_have_adhoc_permission(current_user)
    span class="badge"
      = link_to "Adhoc PM", projects_path(adhoc: true), class: "orange-button large-3 cell", style: "margin: 5px;"
  - if @project.inactive == false || @project.inactive == nil
    span class="badge"
      = link_to 'Deactivate', "/projects/#{@project.id}/deactivate_project", :method => :post, class: "center orange-button large-3 cell", style: "margin: 5px;"
  - elsif @project.inactive == true
    span class="badge"  
      = link_to 'Reactivate', "/projects/#{@project.id}/reactivate_project", :method => :post, class: "center orange-button large-3 cell", style: "margin: 5px;"
  /- if current_user.admin?
  /  = link_to "Admin", "/admin", class: "orange-button large-3 cell", style: "margin: 5px;"
  - if user_represents_customers(current_user) || (can? :manage, Customer)
    span class="badge"
      = link_to "Manage Customers", "customers", class: "orange-button large-3 cell", style: "margin: 5px;" 
  span class="badge"
    = link_to "Vacation Request", "/vacation_request", class: "orange-button large-3 cell", 
    style: "margin: 5px;"
  span class="badge"
    = link_to "Shift Change Request", "/shift_change_request", class: "orange-button large-3 cell", 
    style: "margin: 5px;"
  span class="badge"
    = link_to 'Inventory Report', "/inventory_and_equipment_reports?id=#{@project.id}", :method => :get,class: "center orange-button large-3 cell", style: "margin: 5px;" 
  span class="badge"
    = link_to 'Send Email', send_project_users_email_path(project_id: @project.id), :method => :get, class: "center orange-button large-3 cell",style: "margin: 5px;" 
  
  - if current_user.proxy
    span class="badge"
      = link_to "Manage Proxy Projects", "/users/#{current_user.id}/proxies", class: "orange-button large-3 cell", style: "margin: 5px;" 
  span class="badge"
    = link_to "User Report", "/show_user_reports/#{current_user.id}", class: "orange-button large-3 cell", style: "margin: 5px;"

      
      

app/views/projects/_show_all_projects_form.html.slim
table {id= "project_left_table", class="project_table"}
	thead
		tr
			th Name
			th Customer
			th Inactive?
			th
	tbody{id = "all_projects"}
		== render partial: "all_projects", locals: {projects: @projectsss}	

app/views/projects/_timesheets_for_approval.html.slim
.white-background
	= form_tag approve_all_path, id: "approve_all_form", method: :post, remote: true
		div id= "show_hide" style="display: block;"
			h2 Time Sheets Submitted for Approval
			table class="approve-table table"style="width:90%;"
				thead
				  tr
				  	th Project
				    th Employee
				    th Start date
				    th End date
				    th Hours
				    th
				    th
				    th
				    th

				tbody
					-i = 0
				  	- projects.each do |p|
				  		
						- @applicable_week = Week.joins(:time_entries).where("(weeks.status_id = ? or weeks.status_id = ?) and time_entries.project_id= ? and time_entries.status_id=? and weeks.dismiss=?", "2", "4",p.id,"2", "false").select(:id, :user_id, :start_date, :end_date , :comments, :dismiss).distinct
				  		- @applicable_week.each do |at|
						    tr id = "#{i}"
						    	td
						        	= p.name
						      	
						      	td
						        	= hidden_field_tag "week_id_#{i}", at.id
						        	= hidden_field_tag "user_id_#{i}", at.user_id
						        	= User.find(at.user_id).name
						      	td
						        	= at.start_date.strftime('%Y-%m-%d')
						      	td
						        	= at.end_date.strftime('%Y-%m-%d')
						      	td 
						      		-if TimeEntry.where(week_id: at.id, project_id: p.id).sum(:hours) > 40
							      		= hidden_field_tag "project_id_#{i}", p.id
							        	= button_tag TimeEntry.where(week_id: at.id, project_id: p.id).sum(:hours), id: "show_hours_#{i}", class: "tiny secondary show-hours btn btn-danger", type: "button", data: {toggle: "modal", target: "#showHours"}
							        -else
							        	= hidden_field_tag "project_id_#{i}", p.id
							        	= button_tag TimeEntry.where(week_id: at.id, project_id: p.id).sum(:hours), id: "show_hours_#{i}", class: "tiny secondary show-hours btn btn-info", type: "button", data: {toggle: "modal", target: "#showHours"}
							        - if ExpenseRecord.where("week_id= ? and project_id= ?", at.id,p.id).present?
							        	= image_tag("amount.png", style: "width:28px;float:right;position:relative;top:-32px;left:18px;")

						      	td = link_to "Approve","/projects/#{p.id}/approve/#{at.id}/#{i}", class: "btn btn-primary approve-class orange-button", type: "button", remote: true
						      	
						      	/td = link_to "Reject", "/projects/reject/#{at.id}", class: "reject_class", id:"time_reject_#{i}" , remote: true
						      	td class="reject_div" style="display:none;"
						        	= button_tag "Reject", class: "btn btn-danger reject_class", id:"time_reject_#{i}" , type: "button", remote: true
						      	td
						        	= button_tag "Add Comment to Reject", class: "add_comment btn-secondary tiny", id: "add_comment_#{i}", type: "button"
						      	td
						        	= text_area_tag "comments", at.comments, size: "35x3.5", class: "comment", id: "comment_text_#{i}"

						        td = link_to "X","/weeks/dismiss/#{at.id}/#{i}", class: "dismiss-class red-button", type: "button", remote: true
						    - i +=1	
				    div id="showHours" class="modal" aria-hidden="true" role="dialog"

			= submit_tag "Approve ALL" , :id=> "approve_all_button" , :class=> "approve_all_class"

	div class = "hidden timesheets"
		= link_to "Show All Timesheets","show_all_timesheets", target: :_blank

app/views/projects/_user_inventory_and_equipment.html.erb
<div id="inventoryModel" class= "modal"> 
	<div class = "modal-content">
    <div class="modal-header">
   		<p style="position: relative;text-align: left;float: left;left: 37%;"><strong> Please Add Inventory And Equipment Details!</strong> </p>  
       	<span class = "close inv_close"> &times;</span>
      </div>
      <%= form_tag add_multiple_user_inventory_path , remote: true  do |form| %>
   
        <%= hidden_field_tag "inv_user_ids", sel_inv_ids %>
        <%= hidden_field_tag "project_id", project_id  %> 

        <div class="form-group">
          <label>Add Inventory And Equipment for user(s):</label>
        </div>      
        <table class="table">
          <thead>
          <tr>
              <th>User</th>
              <th>Equipment Name</th>
              <th>Equipment Number:</th>
              <th>Issued Date</th>
             <!--  <th>Submitted Date</th> -->
          </tr>
          </thead>
          <tbody>
          <% inv_users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= text_field_tag "equipment_name_#{user.id}", "", required: true %></td>
              <td><%= text_field_tag "equipment_number_#{user.id}", "" %></td>
              <td><%= date_field_tag("issued_date_#{user.id}", Date.today, required: true )%></td>
             <!--  <td><%= date_field_tag("submitted_date_#{user.id}", Date.today)%></td> -->
            </tr>
          <% end %>
        </tbody>
        </table>
        <%= submit_tag "Add Inventory", class: "btn oragne-button", id: "inventory_button" %>
      <% end %>
    </div>   
  </div> 

app/views/projects/dynamic_project_update.js.erb
$('#dynamic_projects').html("<%= j render(:partial => 'projects/new_edit_form') %>")

app/views/projects/new.html.slim
h1 New project
- if flash[:alert]
  p.alert = alert
div.new_project_page
	- if @configuration.present?
		p What would you like to do

		= radio_button_tag :import_from_system, '', false
		label Import from External Systems
		= radio_button_tag :create_new_project, '', false
		label Create New Project

		div.new_project style="display:none;"
			== render 'new_form'
		div.import style="display:none;"
			== render 'external_system_form'
	-else
		= radio_button_tag :create_new_project, '', false
		label Create New Project

		div.new_project style="display:none;"
			== render 'new_form'
		
= link_to 'Back', projects_path

app/views/projects/permission_denied.html.erb
<h1 id="denied">You are not allowed to access this page.</h1>

app/views/projects/reject_shift_change.js.erb
$("#shift_<%= @row_id %>").hide();

app/views/projects/show.html.slim
p#notice = notice

p
  strong Name:
  = @project.name
p
  strong Customer:
  = @project.customer

= link_to 'Edit', edit_project_path(@project)
'|
= link_to 'Back', projects_path

app/views/projects/update.js.erb
$("#project_name_<%= @project.id %>").text('<%= @project.name %>');
$('#dynamic_projects').html("<%= j render(:partial => 'projects/new_edit_form') %>")

app/views/projects/user_time_report.html.slim
h1 class="row" #{@user.first_name}; #{@user.last_name}'s Time sheets

table class="border"
  thead
    tr
      th Start date
      th End date
      th Status
      th Report


  tbody
    - @weeks.each do |week|
      tr
        td = week.start_date.strftime('%Y-%m-%d')
        td = week.end_date.strftime('%Y-%m-%d')
        td = find_status(week)
        td = link_to "Report", "/weeks/#{week.id}/report" if (find_status(week) == "SUBMITTED") || (find_status(week) == "APPROVED")